appdev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django1.views import MyLogoutView
from django1 import views as list_views
from django1 import views
from django1 import forms

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path(
        "login/",
            auth_views.LoginView.as_view(
            template_name="login.html",
            form_class=forms.AuthenticationForm,
        ),
        name="login",
),
    path(
        "accounts/login/",
            auth_views.LoginView.as_view(
            template_name="login.html",
            form_class=forms.AuthenticationForm,
        ),
        name="login",
),
    path('signout/', MyLogoutView.as_view(), name='signout'), 
    
    path("", list_views.home_page, name="home"),
    path('lists/', include('django1.urls')),
    path('profile/', views.profile, name='profile'), 
    path(
        "item/<int:pk>/delete/", views.ItemDeleteView.as_view(), name="item_delete",
),

]

django1/urls.py
from django.urls import path
from django.views.generic import TemplateView 
from django1 import views

urlpatterns = [
    path("", views.view_list, name="view_list"),
    path("new", views.new_list, name="new_list"),
    path("add_item", views.add_item, name="add_item"),
]

django1/models.py
from django.db import models
from django.conf import settings

from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager,
)

# Create your models here.
class UserManager(BaseUserManager): 
    use_in_migrations = True
    def _create_user(self, email, password,**extra_fields): 
        if not email:
            raise ValueError("The given email must be set") 
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password) 
        user.save(using=self._db) 
        return user
    
    def create_user(self, email, password=None, **extra_fields): 
        extra_fields.setdefault("is_staff", False) 
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)
    
    def create_superuser(self, email, password, **extra_fields): 
        extra_fields.setdefault("is_staff", True) 
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True: 
            raise ValueError(
               "Superuser must have is_staff=True."
           )
        if extra_fields.get("is_superuser") is not True: 
            raise ValueError(
               "Superuser must have is_superuser=True."
           )
        return self._create_user(email, password, **extra_fields)
    
class User(AbstractUser): 
    username = None
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

class Item(models.Model):
    text = models.TextField(default="")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='items_created',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

 

django1/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm as DjangoUserCreationForm
)
from django.contrib.auth.forms import UsernameField
from django.contrib.auth import authenticate
from django.core.mail import send_mail
import logging

from . import models

logger = logging.getLogger(__name__)

class UserCreationForm(DjangoUserCreationForm): 
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}
    
    def send_mail(self): 
        logger.info(
            "Sending signup email for email=%s",
            self.cleaned_data["email"],
        )
        message = "Thank you for joining Appdev{}".format(self.cleaned_data["email"]) 
        send_mail(
            "Thank you for joining Appdev",
            message,
            "app@appdev.dev",
            [self.cleaned_data["email"]],
            fail_silently=True,
)

class AuthenticationForm(forms.Form): 
    email = forms.EmailField() 
    password = forms.CharField(
        strip=False, widget=forms.PasswordInput
    )
    def __init__(self, request=None, *args, **kwargs): 
          self.request = request
          self.user = None
          super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email") 
        password = self.cleaned_data.get("password")

        if email is not None and password: 
            self.user = authenticate(
                self.request, email=email, password=password
        )
            if self.user is None:
                 raise forms.ValidationError(
                   "Invalid email/password combination."
               )
            logger.info(
                "Authentication successful for email=%s", email
            )

        return self.cleaned_data
    
    def get_user(self):
        return self.user

django1/views.py
from django.shortcuts import redirect, render
from django.views.generic.edit import FormView
from django.contrib.auth.views import LogoutView
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.views.generic.edit import (
    FormView,
    CreateView,
    UpdateView,
    DeleteView,
)

from . import forms
from .models import Item
from django1 import models

class SignupView(FormView): 
    template_name = "signup.html" 
    form_class = forms.UserCreationForm
    
    def get_success_url(self):
        redirect_to = self.request.GET.get("next", "/") 
        return redirect_to
    
    def form_valid(self, form):
        response = super().form_valid(form) 
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        user = authenticate(email=email, password=raw_password)

        login(self.request, user)
        form.send_mail()

        messages.info(
            self.request, "You signed up successfully."
        )
        return response

class MyLogoutView(LogoutView): 
    template_name = "logout.html"

def home_page(request):
    items = Item.objects.all().order_by('-updated_at')
    paginator = Paginator(items, 10)
    page = request.GET.get('page')
    items = paginator.get_page(page)
    return render(request, "home.html", {'items': items})

@login_required
def new_list(request):
    if request.method == 'POST':
        Item.objects.create(text=request.POST.get("item_text"), owner=request.user)
        return redirect("/")
    else:
        # If the request method is not POST (e.g., GET), redirect to the login page
        return redirect("login") 


def view_list(request,):
    #our_list = List.objects.get(id=list_id)
    items = Item.objects.all()
    return render(request, "list.html", {'items': items})

@login_required
def add_item(request, ):
   # our_list = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST["item_text"],owner=request.user)
    return redirect(f"/lists/")

class ItemDeleteView(LoginRequiredMixin, DeleteView): 
    template_name = "item_confirm_delete.html" 
    model = models.Item
    success_url = reverse_lazy("profile")

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)

@login_required
def profile(request):
    # Filter items by the current user
    user_items = Item.objects.filter(owner=request.user).order_by('-updated_at')
    paginator = Paginator(user_items, 10)
    page = request.GET.get('page')
    user_items = paginator.get_page(page)
    return render(request, 'profile.html', {'user_items': user_items})

django1/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>
    <title>To-Do lists</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Appdev</a>
       <button
       class="navbar-toggler"
       type="button"
       data-toggle="collapse" data-target="#navbarSupportedContent"> <span class="navbar-toggler-icon"></span>
         </button>
         <div
       class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav mr-auto">
        {% if request.user.is_authenticated %}
        <li
        class="nav-item">
        <a class="nav-link" href="/">Home</a>
        </li>
        <li
        class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>

        <li
        class="nav-item">
        <form method="post" action="{% url 'signout' %}">
          {% csrf_token %}
          <button type="submit" class="nav-link btn btn-link">Logout</button>
      </form>
      
        </li>

        {% else %}
        <li
        class="nav-item">
        <a class="nav-link" href="/">Home</a>
        </li>
        <li
        class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a> </li>
        <li
        class="nav-item">
        <a class="nav-link" href="{% url 'signup' %}">Sign up</a> </li>
        {% endif %}
       </ul> </div>
      
     </nav>
    <div>
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
      <div class="row justify-content-center p-5 bg-body-tertiary rounded-3">
        <div class="col-lg-6 text-center">
          <h1 class="display-1 mb-4">{% block header_text %}{% endblock %}</h1>

          <form method="POST" action="{% block form_action %}{% endblock %}" >
            <input
              class="form-control form-control-lg"
              name="item_text"
              id="id_new_item"
              placeholder="Enter a to-do item"
            />
            {% csrf_token %}
          </form>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          {% block table %}
          {% endblock %}
        </div>
      </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"> </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"> </script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"> </script>

  </body>

</html>

django1/templates/basee.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>
    <title>To-Do lists</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Appdev</a>
       <button
       class="navbar-toggler"
       type="button"
       data-toggle="collapse" data-target="#navbarSupportedContent"> <span class="navbar-toggler-icon"></span>
         </button>
         <div
       class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav mr-auto">
        {% if request.user.is_authenticated %}
        <li
        class="nav-item">
        <a class="nav-link" href="/">Home</a>
        </li>
        <li
        class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>
        <li
        class="nav-item">
        <form method="post" action="{% url 'signout' %}">
          {% csrf_token %}
          <button type="submit" class="nav-link btn btn-link">Logout</button>
      </form>
      
        </li>
        {% else %}
        <li
        class="nav-item">
        <a class="nav-link" href="/">Home</a>
        </li>
        <li
        class="nav-item">
        <a class="nav-link" href="/login/">Login</a> </li>
        <li
        class="nav-item">
        <a class="nav-link" href="/signup/">Sign up</a> </li>
        {% endif %}
       </ul> </div>
      
     </nav>
    <div class="container">

      <div class="row justify-content-center">
        <div class="col-lg-6">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
          {% endfor %}

          {% block content%}
          {% endblock %}
        </div>
  
      </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"> </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"> </script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"> </script>
  </body>

</html>

django1/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}/lists/new{% endblock %}

{% block table %}

    <ul>
        {% for item in items %}
            <li>{{ item.text }} <b>by </b>{{item.owner}} <b>on</b> {{item.created_at}} </li>
            {% empty %}
            <ul>
            <li><h2>No products yet. </h2></li>
            </ul>
                {% endfor %}
    </ul>
    {% if items.paginator.num_pages > 1 %}
    {% include 'pagination.html' with items=items %}
    {% endif %}
{% endblock %}

django1/templates/item_confirm_delete.html
{% extends "basee.html" %} 
{% block content %}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<div class="container">
<h2>Delete Item</h2> 
<form method="POST">
{% csrf_token %}
<p>Are you sure you want to delete it?</p>
<p><button type="submit" class="btn btn-primary">Submit </button></p>
</form>
</div>
{% endblock content %}

django1/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}/lists/add_item{% endblock %}

{% block table %}
<table class="table" id="id_list_table">
  {% for item in item_set.all %}
  <tr>
    <td>{{ forloop.counter }}: {{ item.text }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <label for="item_text">Item Text:</label>
  <input type="text" id="item_text" name="item_text" required>
  <button type="submit">Add Item</button>
</form>
{% endblock %}

django1/templates/login.html
{% extends "basee.html" %}

{% block content %}
    <h2>Login</h2>
    <p>Please fill the form below.</p>

    <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            {{ form.email.label_tag }}
            <input type="email" class="form-control {% if form.email.errors %} is-invalid{% endif %}"
                   id="id_email" name="email" placeholder="Your email"
                   value="{{ form.email.value|default:"" }}">
            {% if form.email.errors %}
                <div class="invalid-feedback">{{ form.email.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.password.label_tag }}
            <input type="password" class="form-control{% if form.password.errors %} is-invalid{% endif %}"
                   id="id_password" name="password" placeholder="Your password"
                   value="{{ form.password.value|default:"" }}">
            {% if form.password.errors %}
                <div class="invalid-feedback">{{ form.password.errors }}</div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

django1/templates/logout.html
{% extends "basee.html" %}
{% block content %}
<h2>You have successfully signed out</h2>
<p>You can  <a href="{% url 'login' %}">sign in</a> again.</p> 

{% endblock content %}

django1/templates/pagination.html
{% if items.paginator.count > 1 %} 
<div class="pagination clearfix">
    {% if items.has_previous %}
    <a class="pagination-action" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
    <i class="fa fa-angle-double-left" aria- hidden="true"></i>
    </a>
    <a class="pagination-action" href="?page={{ items.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
      </i>
    <i class="fa fa-angle-left" aria-hidden="true"> </a>
    {% endif %}
    {% if items.paginator.num_pages > 1 %}
    {% for num in items.paginator.page_range %} 
    {% if items.number == num %}
    <span class="pagination-number pagination-current">{{ num }}</span>
    {% elif num > items.number|add:'-3' and num < items.number|add:'3' %}
    <a class="pagination-number" href="?page={{num}} {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ num }}</a>
    {% endif %}
    {% endfor %}
{% endif %}
{% if items.has_next %}
<a class="pagination-action" href="?page={{items.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
<i class="fa fa-angle-right" aria- hidden="true"></i>
</a>
<a class="pagination-action" href="?page={{ items.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
<i class="fa fa-angle-double-right" aria- hidden="true"></i>
</a>
{% endif %}
</div> 
{% endif %}

django1/templates/profile.html
{% extends "basee.html" %}
{% block content %}

<head>
    <title>Profile</title>
</head>
<body>
    <h2>Your Items:{{ user_items.paginator.count }}</h2>
    <ul>
        {% for item in user_items %}
            <li>{{ item.text }} <b>on</b> {{item.created_at}} <a href="{% url 'item_delete' item.id %}">Delete item</a>
            </a></li>
        {% endfor %}
    </ul>
    {% if user_items.paginator.num_pages > 1 %}
    {% include 'pagination.html' with items=user_items %}
    {% endif %}
</body>
{% endblock content %}

django1/templates/signup.html
{% extends "basee.html" %}

{% block content %}
    <h2>Sign up</h2>
    <p>Please fill the form below to sign up</p>

    <form method="POST">
        {% csrf_token %}

        <div class="form-group">
            {{ form.email.label_tag }}
            <input type="email" class="form-control {% if form.email.errors %} is-invalid{% endif %}"
                   id="id_email" name="email" placeholder="Your email"
                   value="{{ form.email.value|default:"" }}">
            {% if form.email.errors %}
                <div class="invalid-feedback">{{ form.email.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.password1.label_tag }}
            <input type="password" class="form-control {% if form.password1.errors %} is-invalid{% endif %}"
                   id="id_password1" name="password1" placeholder="Type password"
                   value="{{ form.password1.value|default:"" }}">
            {% if form.password1.errors %}
                <div class="invalid-feedback">{{ form.password1.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.password2.label_tag }}
            <input type="password" class="form-control{% if form.password2.errors %} is-invalid{% endif %}"
                   id="id_password2" name="password2" placeholder="Confirm password"
                   value="{{ form.password2.value|default:"" }}">
            {% if form.password2.errors %}
                <div class="invalid-feedback">{{ form.password2.errors }}</div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}